MONITOR_HOST_NAME=$(hostname -f)

ARCHIVE_PREFIX="${MONITOR_HOST_NAME}"
S3_PREFIX="backups/${MONITOR_HOST_NAME}"


BACKUP_SOURCES=(
    "/opt/kumacompose"
)

declare -A DOCKER_COMPOSE_MAP=(
    ["/opt/kumacompose"]="/opt/kumacompose"
    # more to add if needed
)


DOCKER_STOP_TIMEOUT=30
STAGING_DIR="/var/backup/staging/"
LOG_DIR="/var/log/backup/${MONITOR_HOST_NAME}"
MAX_LOG_DAYS=90
KEEP_LOCAL_ARCHIVES=7


RCLONE_REMOTE="s3-deep-archive"
S3_BUCKET="tsdb-backup-da"
S3_STORAGE_CLASS="DEEP_ARCHIVE"
RCLONE_RETRIES=3

